spring:
    application:
        name: stock-watcher
    datasource:
      url: jdbc:h2:mem:stock_watcher
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    flyway:
        enabled: true

server:
    error:
        include-stacktrace: never

logging:
    level:
        root: info

yahoo:
    finance:
        api-key: ExFYHbtghN1LjHCtVq0Ax4ufU6vgoFy82KBGT4OG